# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'takepic.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1678, 1086)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 40, 1536, 864))
        self.label.setText("")
        self.label.setObjectName("label")
        self.picButton = QtWidgets.QPushButton(Form)
        self.picButton.setGeometry(QtCore.QRect(630, 960, 181, 51))
        self.picButton.setObjectName("picButton")
        self.picButton_2 = QtWidgets.QPushButton(Form)
        self.picButton_2.setGeometry(QtCore.QRect(870, 960, 181, 51))
        self.picButton_2.setObjectName("picButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.picButton.setText(_translate("Form", "拍照"))
        self.picButton_2.setText(_translate("Form", "保存"))
